### ISSUE TITLE
Registering a Custom Application

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2241] opened 2021-06-02 16:25 UTC
I'm trying to register a custom application in the Merchant Center. But it does not seem to work, even with a fresh starter project (without customizations apart from the config).

The application is hosted on Azure's static hosting service.

I've also tried without using the /public path, and also uploaded the static files to the public's parent folder of course. But this also didn't work. The whole custom application does work in my local development mode.

The page won't load in the Merchant Center, it's giving a 404 from the static hosting. Probably because the custom application Javascript redirects to a path which doesn't exist on Azure, which also happens if you visit the URL directly. I assume the Merchant Center would load the .../public/index.html file, because ".../public/" is the path I set in the JSON config and the Merchant Center config. But it gives a 404, and doesn't really tell me which it failed to load.

I also tried by switching the hosting to an Azure CDN, to avoid potential issues with CORS. But sadly this also doesn't work

{{More details @ SUPPORT-12487}}

**Comment by tdeekens** [comment] 2021-06-02 17:22
Hi, 

thanks for opening the issue. When using the path without `/public` please wait for about 60m as we have to cache the configuration and it might take some time for it to flush. It's mentioned in the documentation as far as I recall but I sadly don't know here.

Additionally, can you see any logs on your side from traffic being routed to your static asset hosting?

Maybe this solves the issue.

Best,
Tobi

**Comment by JonasDeBondt** [comment] 2021-06-03 07:38
Hi,

I'm the developer who originally submitted a support ticket for this issue on jira.commercetools.com. Waiting for the flush did not work, some of our configurations have been active for over a day before trying something else to no avail. But I've activated the request logging in Azure, and noticed the following behaviour.

In my current test the config is as follows:
`{
    "name": "Fenego Backoffice",
    "entryPointUriPath": "translation-keys",
    "cloudIdentifier": "gcp-eu",
    "env": {
        "production": {
            "url": "https://fenegoctstoragedemo.z6.web.core.windows.net"
        }
    }
}`

Now when configuring the custom application in the Merchant Center I used that same URL. I clicked on the new menu item, which showed the 404 error. I checked the request logging and it seems the MC doesn't request https://fenegoctstoragedemo.z6.web.core.windows.net but it requests fenegoctstoragedemo.z6.web.core.windows.net/**b2c-fashionego/translation-keys**. So it adds the project name, and custom application name to the path... And it looks for the index.html file on that path. So on the static hosting I created a directory "b2c-fashionego" and a subdirectory "translation-keys" and I've uploaded all the static files there. Now clicking the menu item from the MC shows an actual page, **but** now it seems that the application is still looking for the static .js files at https://fenegoctstoragedemo.z6.web.core.windows.net, instead of the path described above. So right now I have the same static files uploaded in both the root folder of the static hosting, and the subdirectories to get it working.

**Comment by tdeekens** [comment] 2021-06-03 07:54
Hi,

thanks for getting back. Could you share the configuration inside the MC you provided? Maybe as a screenshot or the values copied out if possible. I think there is a misconfiguration somewhere 🤔. 

Thanks.

**Comment by JonasDeBondt** [comment] 2021-06-03 07:56
Hi,

For sure!

![image](https://user-images.githubusercontent.com/43641656/120608932-02e73000-c452-11eb-909b-ebd053e9b0b4.png)

**Comment by pa3** [comment] 2021-06-03 11:27
Hey, @JonasDeBondt!

Sadly we still can't spot anything suspicious on the screenshots and other information already provided.

Can you maybe also provide the response of `FetchProjectExtensionsNavbar` query (one of the POST requests to `https://mc-api.europe-west1.gcp.commercetools.com/graphql`) or by running following snippet from your terminal:

```
curl https://mc-api.europe-west1.gcp.commercetools.com/graphql \
--header 'Content-Type: application/json' \
--header 'X-CTP-Access-Token: Bearer YOUR_ACCESS_TOKEN' \
--header 'X-GraphQL-Target: settings' \
--header 'X-Project-Key: YOUR_PROJECT_KEY' \
--request POST \
--data '{"query": "query { projectExtension { id applications(where: { isActive: true }) { id createdAt updatedAt name description url navbarMenu { id key uriPath icon labelAllLocales { locale value } featureToggle permissions submenu { id key uriPath labelAllLocales { locale value } permissions featureToggle } } } } }"}'
``` 

Where `YOUR_ACCESS_TOKEN` is a token created from  `Settings > Developer Settings > API Clients` in MC.

Thanks!

**Comment by tdeekens** [comment] 2021-06-03 11:34
Hi,

thanks. This looks good. In addition what what @pa3 mentions to tap into the previously discussed topics:

The "Main route path" is the `entryPointPath` of the config which is what I wanted to make sure of. Also the `production.url` is the same in the UI and config in `https://fenegoctstoragedemo.z6.web.core.windows.net`. I assume you don't have any "Link Permissions" or sub menus configured as they're not visible in the screenshot? Any reason the config says `Fenego Backoffice` as a `name` and `Translation Keys` in the UI?

I've also verified with other Custom Applications we have internally for testing and other customers that nothing in general is wrong to rule that out.

Attempting to clarify the request routing: there is a proxy in front of all applications which loads the static assets from the application url configured. This uri path of the menu (and browser) is matched and the corresponding custom application receives traffic if present. The traffic towards the custom application should be the application url without project key and/or `entryPointPath`. The React application should then handle the traffic taking into account the `entryPointUriPath` while also having access to the project key if needed.

I tried to quickly reproduce it with the config you have and get a:

<img width="325" alt="CleanShot 2021-06-03 at 13 25 40@2x" src="https://user-images.githubusercontent.com/1877073/120637458-3be1cd80-c46f-11eb-821e-1f90d0022970.png">

Which should come from your application. Is that something you see too? I am not sure it applies in your case from your comments but as you speak of static assets, have you looked at using the `cdnUrl` as documented [here](https://docs.commercetools.com/custom-applications/deployment/serving-static-assets#serving-assets-from-a-remote-cdn-or-cloud-storage)?

Hope this helps somehow.

**Comment by JonasDeBondt** [comment] 2021-06-03 11:54
`{
  "data": {
    "projectExtension": {
      "id": "ckpcp4x2r5t570732w56qe2wf",
      "applications": [
        {
          "id": "ckpe09cquv80n0708itrxkm0a",
          "navbarMenu": {
            "id": "ckpgkd7bo97rk0732vlk0hjtp",
            "key": "translation-keys",
            "uriPath": "translation-keys",
            "icon": "WorldIcon",
            "labelAllLocales": [
              {
                "locale": "en-US",
                "value": "Translation Keys",
                "__typename": "LocalizedField"
              }
            ],
            "featureToggle": null,
            "permissions": [
              "ViewProducts"
            ],
            "submenu": [],
            "__typename": "NavbarMenu"
          },
          "__typename": "ApplicationExtension"
        }
      ],
      "installedApplications": [],
      "__typename": "ProjectExtension"
    }
  }
}`

This is the response I see to the mentioned query.

@tdeekens, I did have a link permission configured, being "ViewProducts". Just for testing purposes. No sub navigation has been configured. No specific reason for the display name to differ, I can change it to "Translation Keys" in the JSON config too but I suppose it won't matter much?

I didn't see a 400 error, only 404s. I'm not sure on which URL you see that 400?

**Comment by tdeekens** [comment] 2021-06-03 12:13
> I didn't see a 400 error, only 404s. I'm not sure on which URL you see that 400?

Just when navigating to a project of my own and entryPointPath I've configured the application in. So basically '<projectKey>/translation-keys' while having access to the project. Can you share a screenshot of what you see with the url maybe?

**Comment by JonasDeBondt** [comment] 2021-06-03 12:19
Currently I can see a functioning custom application, because I uploaded the static files in both the root and the "b2c-fashionego/translation-keys" subfolder. But:

-  I see a 404 when I **don't** upload the static files in the "b2c-fashionego/translation-keys" subfolder. Because CT goes looking there, and they're not there on the static hosting.
- I see a CT loading screen when I **do** upload the static files in that subfolder, and not in the root. But then I'm getting errors because it can't find Javascript files.

Hence my current workaround to upload the files in both directories. I could probably work around this issue using the `cdnUrl` property but this behaviour doesn't seem normal to me?

**Comment by tdeekens** [comment] 2021-06-03 13:06
Thanks for the detailed response. Glad it's working. It's certainly not desired having to upload static assets in both folders and I have not seen anybody having to do it. Not do I know of anything on the configuration side being able to cause it. Maybe the cdnUrl is a work around to solve it. What confuses me a bit is the "CT goes looking there" as I am also unsure what causes the need for the duplication and paths in the first place. Maybe also something on Azure. I myself haven't hosted there yet hence I am guessing :-). 

What does .html file referencing the static assets point to as the runtime script?

**Comment by pa3** [comment] 2021-06-03 15:53
Thanks for the patience with all this back and forth, @JonasDeBondt! 

I personally feel very stupid at the moment, because, well... Custom Apps are Single Page Applications and can't be served as pure static assets. Indeed, CT requests `<YOUR_HOST>/b2c-fashionego/translation-keys` and expects loaded SPA to do routing on front-end. As with any other SPA there should be a backend taking care of serving any route as `index.html` and letting SPA do it's job once loaded. Something like `vercel`'s:

```json
    {
      "src": "/(.*)",
      "dest": "/public/index.html",
      "headers": {
        "Cache-Control": "no-cache"
      }
    }
```

If your are serving your Custom Application as `Static Web App`, you can setup fallback routes similar to the snippet above, as described here: https://docs.microsoft.com/en-us/azure/static-web-apps/configuration

In case you are serving you application as a 'static websites on the blob service' (there one where Azure creates `$web` container for you on an existing storage resource) you can specify `index.html` to be your 'Error document path' as a work-around:

![Screenshot from 2021-06-03 20-49-45](https://user-images.githubusercontent.com/1228431/120674210-4e7af780-c4ad-11eb-8d48-3d246af507d6.png)

The disadvantage of doing so is that navigating directly to `https://fenegoctstoragedemo.z6.web.core.windows.net/whatever/url` will result in infinite loop of redirects. So, I'd go for `Static Web App` option.

Hope that helps, and sorry for being misleading and not seeing source of the issue right away.

**Comment by JonasDeBondt** [comment] 2021-06-04 06:48
@tdeekens, @pa3, thanks for the help with this issue! I chose to set the `cdnUrl` property and keep the static files in the "b2c-fashionego/translation-keys" subdirectory, but I've removed them from the root folder. And it seems to work now

**Comment by tdeekens** [comment] 2021-06-04 06:51
Awesome. Glad we could help. If you're satisfied with the solution please close the issue. We can also re-open it later if needed.

**Comment by JonasDeBondt** [comment] 2021-06-04 14:58
@michaelashe, feel free to close the ticket. As you opened it :-)

Thanks!

**Closed** 2021-06-04 14:59 UTC
