### ISSUE TITLE
Laggy drag and drop within `TabularModalPage`

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/merchant-center-application-kit#873] opened 2019-07-22 08:56 UTC
**Describe the bug**

Drag and drop is laggy within `TabularModalPage`

**To Reproduce**

1. Go to `Products` >  `Any Product Details` > `Variant Details` > `Prices` **Tab**
2. Click on `Columns icon`
4. Move items to or from the columns.

**Expected behavior**
The should move smothely.

**Screenshots**

| Before refactoring to `TabularModalPage` | After refactoring to `TabularModalPage` |
| - | -| 
| ![wit-modal-container](https://user-images.githubusercontent.com/7680511/61619066-673de380-ac6e-11e9-88e8-3ae92db0a968.gif) | ![after-tabular-modal-page](https://user-images.githubusercontent.com/7680511/61619067-673de380-ac6e-11e9-91e0-6f9045ccb76b.gif) |

**Additional context**
This was introduced after theis https://github.com/commercetools/merchant-center-frontend/commit/a210ab340f49ea674ae93320e6386f493912f220

**Comment by emmenko** [comment] 2019-07-22 09:05
Interesting...we should probably check the profiler in the react devtools, to see if we can pin point the cause.

Thanks for reporting!

**Comment by jonnybel** [comment] 2019-07-22 09:37
I'm not sure if it's lagging or if it's the DraggableTags that are just getting incorrectly positioned relative to the mouse cursor.

Everything else seems normal, performance-wise. I'll try to debug this.

**Comment by jonnybel** [comment] 2019-07-22 10:25
Seems to be related to this: https://github.com/atlassian/react-beautiful-dnd/issues/485

**Comment by jonnybel** [comment] 2019-07-22 14:14
Workaround found: https://github.com/commercetools/merchant-center-frontend/pull/7315

Closing.

**Closed by jonnybel** 2019-07-22 14:14 UTC
Labels: ❓ Type: Question, 🐛 Type: Bug
