### ISSUE TITLE
When using "useIsAuthorized" method from Permissions package, It returns wrong warnings.

### ISSUE THREAD

**Issue by praveenkumarct** [commercetools/merchant-center-application-kit#2438] opened 2021-12-20 19:17 UTC
**Describe the issue**

We are seeing warnings which are not clear while using permissions package method "useIsAuthorized".

**To Reproduce**

Code below used to call the method:

`const canViewProducts = useIsAuthorized({
    demandedPermissions: ['ViewProducts']
  });
`
  
**Expected behavior**

As per the warning, It should accept one permission and not return any warning.
Also we should not get the below warning, Since we are not using `shouldMatchSomePermissions`.

` @commercetools-frontend/permissions: It is recommended not to use 'shouldMatchSomePermissions' but instead use the hook, HoC or component multiple times.`

**Screenshots**

<img width="1392" alt="Screenshot 2021-12-20 at 19 53 06" src="https://user-images.githubusercontent.com/72923003/146820580-2e244dd7-10fb-435c-9754-676bf89e7072.png">

**Comment by CarlosCortizasCT** [comment] 2022-03-28 10:25
Hello @praveenkumarct,

Sorry for the late reply.

Could you please let us know which versions are you using for both `@commercetools-frontend/permissions` and `@commercetools-frontend/application-shell-connectors`?

Thanks.

**Comment by praveenkumarct** [comment] 2022-03-28 16:19
Hello @CarlosCortizasCT, 

"@commercetools-frontend/permissions": "20.9.4",
"@commercetools-frontend/application-shell-connectors": "20.9.4"

Regards,

**Comment by CarlosCortizasCT** [comment] 2022-03-29 07:04
Hello @praveenkumarct,

We're trying to find out why you're getting those warnings but it's not clear based on the code snippet you provided.

Could you please double check (perhaps following the stack trace of the warnings) that the original code is the one of your example?
Maybe there are other parts of your application where the hook is used with different parameters.

I just also want to let you know we have newer versions for both packages: currently [21.2.1](https://github.com/commercetools/merchant-center-application-kit/releases)

**Comment by emmenko** [comment] 2022-03-29 07:23
FYI: Some of these warnings come from the navbar itself, as we use `shouldMatchSomePermissions` on purpose.

https://github.com/commercetools/merchant-center-application-kit/blob/39031908822dd29ea8823ad43b119f5d1fdc291e/packages/application-shell/src/components/navbar/navbar.tsx#L363

If it's confusing we can try to prevent these warnings for internal packages.

**Comment by emmenko** [comment] 2022-08-12 18:21
Closing as we found out the root cause (see #2731)

**Closed by emmenko** 2022-08-12 18:21 UTC
Labels: 🐛 Type: Bug, 📞 Type: Customer request
