### ISSUE TITLE
CORS Error Received from Custom Application

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1727] opened 2020-09-09 16:24 UTC
**Describe the issue**

I created a custom application for Merchant Center, deployed it to Google Cloud, and then registered the app in Merchant Center. This was done last week, and everything was working as expected, until this morning. Here’s a screenshot of what the application should look like (got screenshot from my local host dev environment):

![image](https://user-images.githubusercontent.com/29213153/92625642-eb9a5e00-f296-11ea-8c75-3355a493b4e0.png)

Now, when I go to the Merchant Center custom app (the one that’s deployed on Google Cloud and registered in Merchant Center), I see this when I click on Custom Countertops app:

![image](https://user-images.githubusercontent.com/29213153/92625733-0c62b380-f297-11ea-9cb0-8f5f479ae797.png)

Here’s how the registered application is configured:

![image](https://user-images.githubusercontent.com/29213153/92625954-4af86e00-f297-11ea-992e-cce586eb4530.png)

**To Reproduce**

To deploy the custom app, I tried to follow the documented steps as close as possible. It appeared to work up until this morning. The current behavior is caused simply by clicking the Custom Countertops link.

**Expected behavior**

I expect to see the custom application render in a similar manner to what I see in my development environment (showing the table of data).

**Additional context**

Not sure if this is related, but I was a little confused by the documentation related to the transformer-firebase.js. I’m not sure if this did what it was supposed to do.

**Comment by emmenko** [comment] 2020-09-10 06:18
Hmm the CORS error is related to LaunchDarkly, it shouldn't prevent the application from working.

From what I can see in the config, is that the "Main route path" looks odd. I would expect it to be `countertop` instead of `countertop/one`. The subroute `one` should probably be a sub link.

When you change that, please remember that the changes might take up to 30min to be available.
https://docs.commercetools.com/custom-applications/help-needed#changes-to-the-custom-application-are-not-reflected-immediately

**Comment by gborkowski** [comment] 2020-09-10 10:37
I made the change you suggested (removing the /one) and that fixed it!  The reason I added that originally was to force the page to render that particular tab (tab one).  It's not a necessary thing, so I'm fine to drop that.  Thank you very much!

**Comment by tdeekens** [comment] 2020-09-10 10:43
> was to force the page to render that particular tab (tab one)

If I am not mistaken your application can handle this. In your route matching (assuming react-router) you can redirect to the first tab in case no tab is selected.

**Comment by gborkowski** [comment] 2020-09-10 11:05
Hi Tobias - you're right - I was able to add one line in my main view which takes care of this.  Thank you!

**Comment by tdeekens** [comment] 2020-09-10 11:28
Cool. Please close the issue when the problem is solved for you. Thanks!

**Comment by gborkowski** [comment] 2020-09-10 11:38
I closed the support case 9976 - is that all I need to do?

**Comment by emmenko** [comment] 2020-09-10 11:42
The GitHub issue is the important one. In general we strongly recommend to only open a GitHub issue for any question or problem regarding Custom Applications.

Thanks

**Closed** 2020-09-11 07:48 UTC
Labels: 📞 Type: Customer request
