### ISSUE TITLE
Proxy to External Graphql API using Graphql endpoint

### ISSUE THREAD

**Issue by Simba14** [commercetools/merchant-center-application-kit#1310] opened 2020-02-04 17:28 UTC
**Describe the bug**
I am trying to to proxy authenticated requests to my own external Graphql API, such as described in the [documentation](https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api) with the REST use case.

I can successfully hit my API using the using a custom client for **unauthorised requests**.
I am struggling to hit the Commerce tools Graphql endpoint in order to forward authenticated requests to my own custom API. 

How does the following translate when using Graphql? 
```
fetch(`https://mc-api.commercetools.com/proxy/forward-to`, {
  method: 'GET',
  headers: {
    Accept: 'application/json',
    'X-Forward-To': 'https://my-custom-app.com/foo/bar',
  },
  credentials: 'include',
});
```
I've tried multiple methods. I'm hoping to achieve something like below.

```
// custom-apollo-client.js

const cache = new InMemoryCache({ addTypename: false });
const link = createUploadLink({
  uri: 'https://mc-api.commercetools.com/proxy/forward-to',
  credentials: 'include',
});

const client = new ApolloClient({
  cache,
  link,
  request: operation =>
    operation.setContext({
      headers: {
        'X-Graphql-Target': 'mc',
        'X-Forward-To': 'https://my-api/graphqll',
      },
    }),
});
export default client;

// Component.js
import customClient from './customClient';

const UPLOAD_FILE = gql`
  mutation upload($file: Upload!) {
    upload(file: $file) {
      name
  }
}
`;
....
<Mutation mutation={UPLOAD_FILE} client={customClient}>
 ....
```

I cannot deploy an important feature without requests being authenticated, so I would really appreciate any help or feedback on how to do this in a graphql environment.

**Comment by emmenko** [comment] 2020-02-04 17:42
Hi @Simba14 ,

The idea with the forward-to proxy is to make requests to your own server and make sure that requests to it are authenticated on behalf of a user.

Once the request hits your backend, and you have verified the JWT, you are "on your own", you don't need to use the Merchant Center API Gateway anymore.
This means that you can make API requests to the commercetools platform from your backend directly. You obviously need client credentials for the projects that you need to work with.

If you are looking into hitting the MC API Gateway from your own server, I'm afraid this is not possible at the moment.

As for your code example, everything looks good. You can remove the `'X-Graphql-Target': 'mc'` as you won't be needing this.

Have I got your problem correctly or did you intend to do things differently?

**Comment by jortizsao** [comment] 2020-02-04 17:54
Hi @emmenko, thank you for quick reply.  

do you know if this forward-to proxy gateway works with multipart requests? we are getting a HTTP 406 error from `https://mc-api.commercetools.com/proxy/forward-to`

**Comment by emmenko** [comment] 2020-02-04 17:56
Hmm good point, I don't think it's currently configured. We'll look into it and get back to you.

**Comment by emmenko** [comment] 2020-02-05 11:21
@Simba14 @jortizsao we might have a fix that we will roll out today. I'll ping you when it's live so that you can give it another try.

**Comment by jortizsao** [comment] 2020-02-05 11:22
Hey @emmenko  great! thank you so much 😃

**Comment by emmenko** [comment] 2020-02-05 13:39
@Simba14 @jortizsao alright the change is live. Please try again from your side and let us know if you still have issues.

**Comment by jortizsao** [comment] 2020-02-06 09:50
Thank you @emmenko . We couldn't test it yet, hopefully tomorrow or next week will do it

**Comment by emmenko** [comment] 2020-02-24 11:17
@jortizsao hi, have you had a chance to test this? Should we close the issue in case the problem is solved?

**Comment by jortizsao** [comment] 2020-02-24 12:20
@emmenko We haven't had time to test it yet. Can you give us until the end of the week?  I commit to test it by then

**Comment by emmenko** [comment] 2020-02-24 12:26
Sure no worries

**Comment by emmenko** [comment] 2020-04-14 16:01
Hi @jortizsao, is this issue still relevant for you? I'm going to close it now, let me know if we should re-open this.
Thanks

**Closed by emmenko** 2020-04-14 16:01 UTC
Labels: ❓ Type: Question, 📞 Type: Customer request
