### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Meghana-aspire** [commercetools/merchant-center-application-kit#2890] opened 2022-11-21 10:16 UTC
I tried to extend merchant centre using merchant-center-application-kit after running npm start I am getting error like this, Please help me to resolve this.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/107937315/203024657-db3e0d7d-a7ff-48b4-af26-3342fca3b4d0.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/107937315/203024928-0568b5bf-efd1-408b-a6d8-85ba0bf542fb.png)

**Comment by emmenko** [comment] 2022-11-21 10:57
Duplicate of #2885

**Closed by emmenko** 2022-11-21 10:57 UTC
Labels: 📞 Type: Customer request
