### ISSUE TITLE
Since today: view_project_settings scope required when requesting project settings

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1861] opened 2020-11-09 16:11 UTC
**Describe the issue**

Recently, we have developed a custom Merchant Center Application that performs an REST API call to an external service.

To get the required parameters, we request the currencies of the current CT project with the react client. The user is an admin of the current site.

This setup worked fine until (around) today. We now get the following error from the API: "Insufficient scope. One of the following scopes is missing: view_project_settings."

Has something changed on your end? How can we retrieve the project settings/currencies with the react client as an admin?

**To Reproduce**
Here's a screenshot of our code to make the request:

![image](https://user-images.githubusercontent.com/29213153/98565638-d1233780-227b-11eb-91ad-fc6ed5c16671.png)

For the custom app we get the currencies from the project with the code as in the screenshot, as you can see we do check if the user has access but this does not seem to matter.

We have this issue on our CT envs and also have it locally when developing the custom app.

**Expected behavior**

To retrieve the currencies has had been the case up until recently.

**Additional context**

**Comment by tdeekens** [comment] 2020-11-09 16:17
> Has something changed on your end? How can we retrieve the project settings/currencies with the react client as an admin?

Nothing has changed on the sides of Custom Applications. Also not on the side of the Merchant Center itself. 

A `view_project_settings` scope has long been required when getting a project. Also documented [here](https://docs.commercetools.com/api/projects/project#get-project). The respective scope is granted on the token by the MC if the user has the `View Project Settings` permission. 

1. You said the user is an Admin in the organization and hence of the project?
2. Can you try logging in and out again (this would trigger a new token generation)

**Comment by emmenko** [comment] 2020-11-09 19:13
> For the custom app we get the currencies from the project with the code as in the screenshot

Regardless of the reported "issue", some project information are available by default to all Custom Application, in the so-called **application context**.

To access it:

```js
import { useApplicationContext } from '@commercetools-frontend/application-shell-connectors';

const MyComponent = () => {
  const projectCurrencies = useApplicationContext(context => context.project.currencies);

  return <>{...}</>
}
```

**Comment by emmenko** [comment] 2020-11-09 19:16
PS: I opened an issue for our team to improve the docs #1862

**Comment by TriPSs** [comment] 2020-11-10 07:37
Thanks @emmenko, using `const projectCurrencies = useApplicationContext(context => context.project.currencies);` solved our issue.

**Comment by emmenko** [comment] 2020-11-10 09:33
Great!

PS: regarding the "insufficient scopes" issue, were you able to solve it? Have you tried logging out and in again?
It would help us to try to understand the issue a bit better. Thanks

**Comment by TriPSs** [comment] 2020-11-10 09:51
@emmenko no that did not help, we had this issue locally and in the released CT app.

**Comment by woutor** [comment] 2020-11-10 09:54
Hi @emmenko, regarding the "insufficient scopes", I have opened the page in an Incognito window, but that didn't help. I thought the error may be related to the platform/scope change of the 2nd of November documented here: https://docs.commercetools.com/api/releases.

Btw, we now run successfully with `useApplicationContext`

**Comment by emmenko** [comment] 2020-11-10 10:15
Hmm so does it mean that you now consistently get this error? And you said you are in the administrators team?

**Comment by woutor** [comment] 2020-11-10 10:23
Yes, we also got the error in an Incognito window after logging in as an admin, on both production and local/development environments.

We now have changed the code as suggested.

**Comment by tdeekens** [comment] 2020-11-10 10:32
Ok, I think we have to work on a reproduction on our side somehow. We do pretty much the same for the Project Settings section of the MC and rely on the same scopes there and are loading currencies there too and haven't heard of any issues from anybody there 🤔.

**Comment by emmenko** [comment] 2020-11-10 10:41
You're using the REST API endpoint the fetch the project info, right?

**Comment by TriPSs** [comment] 2020-11-11 12:04
@emmenko that is correct.

**Comment by emmenko** [comment] 2021-05-14 17:22
Closing as I assume the issue is not there anymore.

**Closed by emmenko** 2021-05-14 17:22 UTC
Labels: 📞 Type: Customer request
