### ISSUE TITLE
The local custom application gives "Not enough permissions to access this resource" error

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2592] opened 2022-05-05 16:58 UTC
We receive the "Not enough permissions to access this resource" error and we are not able view custom application even after giving permission to it.

We have routes file and is with useIsAuthorized, we are upgrading the commerce tools library to V21 as per the instruction - https://docs.commercetools.com/custom-applications/releases/2022-02-02-custom-applications-v21. 

Attaching the routes file.

```js
import React from 'react';
import PropTypes from 'prop-types';
import { Route, Switch } from 'react-router-dom';
import { useIsAuthorized } from '@commercetools-frontend/permissions';
import LockedDiamondSVG from '@commercetools-frontend/assets/images/locked-diamond.svg';
import { MaintenancePageLayout } from '@commercetools-frontend/application-components';
import MainView from './components/main-view';
import { PERMISSIONS } from './constants';

const PageUnauthorized = () => (
  <MaintenancePageLayout
    imageSrc={LockedDiamondSVG}
    title="Not enough permissions to access this resource"
    paragraph1="We recommend to contact your project administrators for further questions."
  />
);

const ApplicationRoutes = ({ match }) => {
  const canViewProducts = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.ViewProducts],
    shouldMatchSomePermissions: true,
  });
  if (!canViewProducts) {
    return <PageUnauthorized />;
  }
  return (
    <Switch>
      <Route
        path={`${match.path}/some-other-route`}
        render={() => <div>{'Nothing to see'}</div>}
      />
      <Route render={routerProps => <MainView match={routerProps.match} />} />
    </Switch>
  );
};
ApplicationRoutes.displayName = 'ApplicationRoutes';
ApplicationRoutes.propTypes = {
  match: PropTypes.shape({
    path: PropTypes.string,
    params: PropTypes.shape({
      projectKey: PropTypes.string.isRequired,
    }).isRequired,
  }).isRequired,
};

export default ApplicationRoutes;
```

Here's the `constant.js` file

```js
export const PERMISSIONS = {
  ManageProducts: 'ManageProducts',
  ViewProducts: 'ViewProducts',
};
```

Is there any insight you can provide?

{{SUPPORT-16331}}

**Comment by Rhotimee** [comment] 2022-05-06 13:51
Hello @michaelashe,

The issue is that the `ViewProducts` permission cannot be used anymore in Org-level Custom Applications. Please make sure you read the [Migrate user permissions](https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications#migrate-user-permissions) section about why and how to migrate.

Furthermore, this "view permission" check can be omitted as it's now done by default by the `<ApplicationShell>`.

**Comment by mmaltsev-ct** [comment] 2022-06-16 16:02
Based on the discussion in the Support ticket, the problem was resolved. Closing the issue. Thanks @Rhotimee.

**Closed by mmaltsev-ct** 2022-06-16 16:02 UTC
Labels: 📞 Type: Customer request
